- name: Install Code Server
  hosts: all
  become: yes

  vars:
    # Use the actual HOME of the user running code-server (root -> /root, fred -> /home/fred)
    code_server_config_dir: "{{ ansible_env.HOME }}/.config/code-server"
    
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - curl
          - wget
        update_cache: yes

    - name: Download code-server install script
      shell: |
        curl -fsSL https://code-server.dev/install.sh | sh
      args:
        creates: /usr/bin/code-server

    - name: Create code-server config directory
      file:
        path: "{{ code_server_config_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Configure code-server
      copy:
        dest: "{{ code_server_config_dir }}/config.yaml"
        content: |
          bind-addr: 0.0.0.0:{{code_server_port}}
          auth: password
          password: {{code_server_pass}}
          cert: false
        owner: "{{ansible_user}}"
        group: "{{ansible_user}}"
        mode: '0600'

    - name: Enable and start code-server service
      systemd:
        name: code-server@{{ansible_user}}
        enabled: yes
        state: started
      become: yes

    - name: Reload and restart nginx service
      systemd:
        daemon_reload: yes
        name: code-server@{{ansible_user}}
        state: restarted
      become: yes

    - name: link go to /usr/local/bin/code-server, /usr/local/share/code-server
      file: 
        src: /usr/bin/code-server
        dest: /usr/local/bin/code-server
        state: link