- name: Install Golang
  hosts: all
  become: yes          # run all tasks with sudo
  become_method: sudo  # optional, default

  vars:
    golang_dir: /usr/local/share/lang
    golang_tar_url: "https://go.dev/dl/go1.25.5.linux-amd64.tar.gz"

  tasks:
    - name: Check connectivity
      ansible.builtin.ping:

    - name: Check if golang directory exists
      ansible.builtin.stat:
        path: "{{ golang_dir }}"
      register: golang_dir_stat

    - name: Print result
      ansible.builtin.debug:
        msg: "golang_dir exists? {{ golang_dir_stat.stat.exists }}"

    - name: Create golang directory (if not exists)
      ansible.builtin.file:
        path: "{{ golang_dir }}"
        state: directory
        mode: '1777'

    - name: Download and unarchive Golang (only if dir was absent)
      ansible.builtin.unarchive:
        src: "{{ golang_tar_url }}"
        dest: "{{ golang_dir }}"
        remote_src: yes
        extra_opts:
          - --strip-components=1
      when: not golang_dir_stat.stat.exists

    - name: Link go to /usr/local/bin, /usr/local/share/lang/bin/go
      file:
        src: /usr/local/share/lang/go/bin/go
        dest: /usr/local/bin/go
        state: link

    - name: Executing arbitrary command (only if /tmp/ip.txt does not exist)
      ansible.builtin.shell: "ip addr > /tmp/ip.txt"
      args:
        creates: /tmp/ip.txt
